//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.CMD.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitness.CMD.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What do you want to do?.
        /// </summary>
        internal static string ActQuestion {
            get {
                return ResourceManager.GetString("ActQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount of attempts is exhausted!.
        /// </summary>
        internal static string ErrorMessage1 {
            get {
                return ResourceManager.GetString("ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong data are entered. Amount of attempts is exhausted!.
        /// </summary>
        internal static string ErrorMessage2 {
            get {
                return ResourceManager.GetString("ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на date and time to start.
        /// </summary>
        internal static string ExerciseBegin {
            get {
                return ResourceManager.GetString("ExerciseBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на date and time to finish.
        /// </summary>
        internal static string ExerciseEnd {
            get {
                return ResourceManager.GetString("ExerciseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на consumption energy per minute (in calories).
        /// </summary>
        internal static string ExerciseEnergy {
            get {
                return ResourceManager.GetString("ExerciseEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на exercise&apos;s name.
        /// </summary>
        internal static string ExerciseName {
            get {
                return ResourceManager.GetString("ExerciseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на amount of calorific in portion of product (in calories).
        /// </summary>
        internal static string FoodCalories {
            get {
                return ResourceManager.GetString("FoodCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на amount of carbohydrates in portion of product (in grammes).
        /// </summary>
        internal static string FoodCarbohydrates {
            get {
                return ResourceManager.GetString("FoodCarbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на amount of fats in portion of product (in grammes).
        /// </summary>
        internal static string FoodFats {
            get {
                return ResourceManager.GetString("FoodFats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на name of product.
        /// </summary>
        internal static string FoodName {
            get {
                return ResourceManager.GetString("FoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на amount of proteins in portion of product (in grammes).
        /// </summary>
        internal static string FoodProteins {
            get {
                return ResourceManager.GetString("FoodProteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на weight of portion of product (in grammes).
        /// </summary>
        internal static string FoodWeight {
            get {
                return ResourceManager.GetString("FoodWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --------------------------------------------------------.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E - enter eating data.
        /// </summary>
        internal static string Select1 {
            get {
                return ResourceManager.GetString("Select1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A - enter activity.
        /// </summary>
        internal static string Select2 {
            get {
                return ResourceManager.GetString("Select2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Q - exit.
        /// </summary>
        internal static string Select3 {
            get {
                return ResourceManager.GetString("Select3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user&apos;s birthday.
        /// </summary>
        internal static string UserBirthday {
            get {
                return ResourceManager.GetString("UserBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user&apos;s gender.
        /// </summary>
        internal static string UserGender {
            get {
                return ResourceManager.GetString("UserGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user&apos;s height.
        /// </summary>
        internal static string UserHeight {
            get {
                return ResourceManager.GetString("UserHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user&apos;s name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user&apos;s weight.
        /// </summary>
        internal static string UserWeight {
            get {
                return ResourceManager.GetString("UserWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Fitness App welcomes you.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
